CREATE OR REPLACE TABLE GIC.INSIGHTS.BOND_REFERENCES (
	SECURITY_NAME VARCHAR,
	ISIN VARCHAR,
	SEDOL VARCHAR,
	COUNTRY	VARCHAR,
	COUPON FLOAT,
	MATURITY_DATE VARCHAR,
	COUPON FREQUENCY VARCHAR,
	SECTOR VARCHAR,
	CURRENCY VARCHAR
);