CREATE OR REPLACE TABLE GIC.INTERMEDIATE.EXTERNAL_FUNDS (
    DATE DATE,
    FINANCIAL_TYPE VARCHAR,
    SYMBOL VARCHAR,
    SECURITY_NAME VARCHAR,
    ISIN VARCHAR,
    PRICE FLOAT,
    QUANTITY FLOAT,
    REALISED_PL FLOAT,
    MARKET_VALUE FLOAT,
    FUND VARCHAR
);