CREATE OR REPLACE VIEW GIC.INSIGHTS.RECONCILIATION_REPORT (
    DATE DATE,
    FINANCIAL_TYPE VARCHAR,
    SECURITY_NAME VARCHAR,
    REF_PRICE FLOAT,
    FUND_PRICE FLOAT,
    PRICE_DIFF FLOAT,
    FUND VARCHAR
) AS
SELECT 
GIC.INTERMEDIATE.EXTERNAL_FUNDS.DATEMTH,
GIC.INTERMEDIATE.EXTERNAL_FUNDS.FINANCIAL_TYPE,
GIC.INTERMEDIATE.EXTERNAL_FUNDS.SECURITY_NAME,
CASE 
    WHEN GIC.INTERMEDIATE.EXTERNAL_FUNDS.SEDOL = '',
        THEN GIC.INSIGHTS.EQUITY_PRICES
    ELSE 
        GIC.INSIGHTS.BOND_PRICES
    END AS REF_PRICE,
GIC.INTERMEDIATE.EXTERNAL_FUNDS.PRICE AS FUND_PRICE,
REF_PRICE - FUND_PRICE AS PRICE_DIFF,
GIC.INTERMEDIATE.EXTERNAL_FUNDS.FUNDS
FROM 
GIC.INTERMEDIATE.EXTERNAL_FUNDS
LEFT JOIN GIC.INSIGHTS.EQUITY_PRICES
    ON GIC.INTERMEDIATE.EXTERNAL_FUNDS.DATE = GIC.INSIGHTS.EQUITY_PRICES.DATETIME
    AND GIC.INTERMEDIATE.EXTERNAL_FUNDS.SYMBOL = GIC.INSIGHTS.EQUITY_PRICES.SYMBOL
LEFT JOIN GIC.INSIGHTS.BOND_PRICES
    ON GIC.INTERMEDIATE.EXTERNAL_FUNDS.DATE = GIC.INSIGHTS.BOND_PRICES.DATETIME
    AND GIC.INTERMEDIATE.EXTERNAL_FUNDS.SEDOL = GIC.INSIGHTS.BOND_PRICES.SEDOL
;